.circleci/config.yml
MAINTAINERS.md
command/dump.go
command/load.go
command/main.go
command/map.go
command/process.go
command/version.go
db_client.go
db_exec.go
db_util.go
db_util_test.go
generator.go
generator_test.go
loader.go
loader_test.go
main_test.go
mapper.go
mapper_test.go
processors.go
processors_test.go
s3.go
version.go

Fixes for issue #3. Need to clean up these linting errors so we can add ```golint``` to the CI pathway.

#3/enhancement/fix linting issues

---

.circleci/config.yml
db_client.go
db_exec_test.go
generator_test.go
loader_test.go
main_test.go
shared_test.go

This addresses all issues with #12 and #9

Issue 12/bugfix/fix circle ci false negatives

---

processors.go
processors_test.go

This has been causing too many issues and slowing down dev. Will add this back later after I do some more research.

Removing Jaro-Winkler

---

db_client_test.go
db_exec_test.go
db_util_test.go
generator_test.go
loader_test.go
main_test.go
mapper_test.go
processors_test.go
version_test.go

Signed-off-by: u5surf <u5.horie@gmail.com>
fix #10

change to testify.Require #10

---

mapper.go

This should take care of schemas, tables, and columns

Fix schemas and columns as well

---

.circleci/config.yml
db_exec.go
db_exec_test.go
generator.go
main_test.go
testing/test_sql_command_file.sql

Mutipart Diff
--
Clean up error checking in db_exec.go
Adding fix for using -f
Remove unused variable
Fix works

 Levi/fix for task #44

---

README.md

This should help with confusion around key mapping

Updating documentation to better explain key mapping

---

go.mod
go.sum

Signed-off-by: Oliver Tso <olivertsor@gmail.com>

Apply go mod tidy

---

README.md
main_test.go
processors.go
processors_test.go

This PR adds a new processor to generate fake IPv4 addresses.
The processor uses fake's built-in function IPv4().

Adds ipv4 processor.

---

generator.go

Remove auto append public schema

---

README.md
main_test.go
processors.go
processors_test.go

Adding an empy JSON processor in order to erase sensitive JSON columns.

Add empty json processor

---

README.md
main_test.go
processors.go
processors_test.go
testing/test_db.sql
testing/test_map.json

Adding an random boolean processor.

Add random bool processor

---

README.md
cmd/process.go
concurrent.go
concurrent_test.go
docs/demos/dellstore2/gonymizer_config.json
generator.go
generator_test.go
go.mod
processors.go
processors_test.go

- Refactors argument passing for ProcessDump.
- Make data structures in processors concurrency safe.
- Add concurrent processor + tests.
- Update README and example config.

Add concurrent processor

---

processors.go

Here is the fix for lint problem caused by my previous PR.

Satisfy lint by handling error from string builder write (never happens)

---

Dockerfile

In response to @endophage comments on https://github.com/smithoss/gonymizer/pull/97

update Dockerfile to use Alpine instead of Golang image

---

README.md
args_builder_test.go
main_test.go

Apologies, i hard coded the username / password i had been using, forgetting that the way others do credentials may be different!
to solve this i changed the config in this test to use its own internal PGConfig struct which has fixed values (I think this makes more sense in here as the one in main_test is for the more "integration" style tests?)

Fixing broken unit test for arg_builder

---

.circleci/config.yml
cmd/main.go
db_exec.go
generator_test.go
mapper.go

- Switching to cimg from circleci dockerhub org (as per: https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/)
- installing version 13 of psql to be compatible with the new docker postgresql server
- updating the go linter to be installed via the recommended script as the goreleaser is deprecated
- fixing some lint issues that the new version of the linter picked up (i hope these are ok, i wasn't 100% sure on some of them)
- fixing a bug in my test where i used the wrong file
This build now passes on CircleCI!
It might be good to run your CI build for pull requests also? as it would have forced me to make these changes with my initial one rather than leaving you to fix master (sorry about that!)

fixing and updating CI

---

.circleci/config.yml

Update golangci-lint to 1.53.3

fix: update golangci-lint

---

README.md
processors.go
processors_test.go

Add UniqueAlphaNumericScrambler

---

processors.go
processors_test.go

Fixes lint issues introduced in #325.

Fix issues from alphanumeric PR
